services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python haijack.py
    envVars:
      - key: BOT_TOKEN
        value: 8543681427:AAF23GGo0ioNexLCDCGHhh0WmIfcV7l2xPM
    plan: free
